name: Publish NPM Package (pnpm)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.21.1
          registry-url: https://registry.npmjs.org/

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.20.0

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 项目打包编译
        run: pnpm run build 

      - name: 发布到 NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --no-git-checks